export const ENVIRONMENT_PRESETS = Object.freeze({
  summer: Object.freeze({
    id: 'summer',
    name: 'קיץ בהיר',
    description: 'שמיים בהירים, שמש חמה וצללים חדים.',
    hdri: null,
    remote: 'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/2k/kloofendal_48d_partly_cloudy_puresky_2k.hdr',
    sunAzimuth: 38,
    sunElevation: 48,
    sunIntensity: 2.9,
    sunColor: '#fff2cf',
    exposure: 1.0,
    environmentIntensity: 0.30,
    backgroundIntensity: 0.68,
    backgroundBlurriness: 0.02,
    hemiIntensity: 0.14,
    fillIntensity: 0.04,
    fogEnabled: false,
    fogDensity: 0.00035,
  }),
  golden: Object.freeze({
    id: 'golden',
    name: 'שעת זהב',
    description: 'שמש נמוכה וחמה עם צללים ארוכים.',
    hdri: null,
    remote: 'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/2k/sunflowers_puresky_2k.hdr',
    sunAzimuth: 62,
    sunElevation: 16,
    sunIntensity: 2.35,
    sunColor: '#ffd29a',
    exposure: 0.92,
    environmentIntensity: 0.24,
    backgroundIntensity: 0.58,
    backgroundBlurriness: 0.03,
    hemiIntensity: 0.11,
    fillIntensity: 0.055,
    fogEnabled: false,
    fogDensity: 0.0005,
  }),
  cloudy: Object.freeze({
    id: 'cloudy',
    name: 'מעונן רך',
    description: 'תאורה רכה, ניגודיות נמוכה וצללים עדינים.',
    hdri: null,
    remote: 'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/2k/overcast_soil_puresky_2k.hdr',
    sunAzimuth: 28,
    sunElevation: 42,
    sunIntensity: 1.25,
    sunColor: '#eef4ff',
    exposure: 0.9,
    environmentIntensity: 0.42,
    backgroundIntensity: 0.62,
    backgroundBlurriness: 0.08,
    hemiIntensity: 0.18,
    fillIntensity: 0.08,
    fogEnabled: false,
    fogDensity: 0.00062,
  }),
  dramatic: Object.freeze({
    id: 'dramatic',
    name: 'דרמטי',
    description: 'עננים חזקים, תאורה כיוונית וניגודיות קולנועית.',
    hdri: null,
    remote: 'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/2k/kloppenheim_06_puresky_2k.hdr',
    sunAzimuth: 115,
    sunElevation: 28,
    sunIntensity: 2.15,
    sunColor: '#ffe0bc',
    exposure: 0.86,
    environmentIntensity: 0.22,
    backgroundIntensity: 0.56,
    backgroundBlurriness: 0.04,
    hemiIntensity: 0.1,
    fillIntensity: 0.035,
    fogEnabled: false,
    fogDensity: 0.00048,
  }),
  procedural: Object.freeze({
    id: 'procedural',
    name: 'שמיים פרוצדורליים',
    description: 'ללא HDRI. שמיים מאוזנים שנוצרים בתוך המנוע.',
    hdri: null,
    remote: null,
    sunAzimuth: 38,
    sunElevation: 48,
    sunIntensity: 2.55,
    sunColor: '#fff0cc',
    exposure: 0.95,
    environmentIntensity: 0,
    backgroundIntensity: 1,
    backgroundBlurriness: 0,
    hemiIntensity: 0.72,
    fillIntensity: 0.08,
    fogEnabled: false,
    fogDensity: 0.00042,
  }),
});

export function getEnvironmentPreset(id) {
  return ENVIRONMENT_PRESETS[id] ?? ENVIRONMENT_PRESETS.summer;
}
